const ADD_CONTACT: string = "ADD_CONTACT";
const DELETE_CONTACT: string = "DELETE_CONTACT";
const GET_CONTACT: string = "GET_CONTACT";
const UPDATE_CONTACT: string = "UPDATE_CONTACT";

export { ADD_CONTACT, DELETE_CONTACT, GET_CONTACT, UPDATE_CONTACT };
