const ADD_CONTACT = "ADD_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const GET_CONTACT = "GET_CONTACT";
const UPDATE_CONTACT = "UPDATE_CONTACT";

export { ADD_CONTACT, DELETE_CONTACT, GET_CONTACT, UPDATE_CONTACT };
